# Generated by Django 4.0.6 on 2022-07-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nametags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
