name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.5]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-cache-dir
    - name: Run Linters
      run: |
        cd ./tagmi/
        pylint --load-plugins pylint_django --ignore-paths="nametags/migrations" --django-settings-module=tagmi.settings ./tagmi/ ./nametags/
        flake8 --extend-exclude "migrations" ./
    - name: Run Tests
      run: |
        mv dev.env .env
        python manage.py test
